#Workshop 0
### Name: Nayanika Dubey
### University ID: 2408008


# Data Types in Python.

### Difference between Mutable and Immutable Data Types.

In [1]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)
# Trying to modify the tuple (will raise an error)
# my_tuple.append(4) # Uncommenting this line will raise an AttributeError

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


### Data Types - Numeric

In [2]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


### Data Types - Sequence - String

In [4]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


### Data Types - Sequence - List

In [5]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

### Data Types - Sequence - Tuple

In [8]:
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
# colors[0] = 'purple'
colors # will generate an error as tuple is immutable.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


('red', 'green', 'yellow', 'blue')

### Data Types - Sequence - Dict

In [9]:
person = {'name':'John','age':30,'city':'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


### Data Types - Set

In [10]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


### Data Types - Boolean

In [11]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


### Data Types - Boolean

In [12]:
result = None

## Logical Statements and Loops.

### Sample Code - if-else statement

In [14]:
num = 10
if num > 0:
  print("Positive")
elif num == 0:
  print("Zero")
else:
  print("Non-positive")

Positive


### Sample Code - Comparision Operator

In [15]:
x = 5
y = 10
if x > 0 and y < 20:
  print("Both conditions are true")
if x > 0 or y > 20:
  print("At least one condition is true")
if not x == 0:
  print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


### Sample Code - Logical Operator

In [16]:
# Define two boolean variables
a = True
b = False
# Using the ’and’ operator
if a and b:
  print("Both a and b are True")
else:
  print("Either a or b is False") # This will be printed
# Using the ’or’ operator
if a or b:
  print("At least one of a or b is True") # This will be printed
else:
  print("Both a and b are False")
# Using the ’not’ operator
if not a:
  print("a is False") # This will not be printed
else:
  print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


### Sample Code - Various Loops

In [18]:
# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
  print(fruit)
# While loop:
count = 0
while count < 5:
  print("Count is:", count)
  count += 1
# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
  print(fruit)
  if fruit == "apple":
    break
# Continiue
print("loop 2")
for fruit in fruits:
  if fruit == "apple":
    continue
  else:
    print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


## Function

### Correct way to Write Function

In [20]:
def add_binary(a, b):
  '''
  Returns the sum of two decimal numbers in binary digits.
  Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer
  Returns:
    binary_sum (str): Binary string of the sum of a and b
  '''
  binary_sum = bin(a+b)[2:]
  return binary_sum

### Example on Built - in - Function

In [21]:
print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
data_type = type(42) # Output: <class ’int’>
total = sum([1, 2, 3]) # Output: 6

Hello, World!


### Example on Built - in - Methods

In [22]:
# str.upper(): Converts all characters in a string to uppercase.
message = "hello".upper() # Output: "HELLO"
# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry") # Output: ["apple", "banana", "cherry"]
# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "Alice", "age": 25}
age = info.get("age") # Output: 25

### Example of well-structured user-defined function

In [23]:
def temperature_converter():
  '''
  Converts temperature between Celsius and Fahrenheit.
  This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
  Fahrenheit to Celsius)
  and then asks for the temperature value. It calculates and returns the converted temperature.
  Returns:
  float: The converted temperature value.
  '''
  print("Choose conversion type:")
  print("1. Celsius to Fahrenheit")
  print("2. Fahrenheit to Celsius")
  # Get conversion choice from user
  choice = input("Enter 1 or 2: ")
  if choice == "1":
    # Celsius to Fahrenheit conversion
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}C is equal to {fahrenheit}F")
    return fahrenheit
  elif choice == "2":
    # Fahrenheit to Celsius conversion
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print(f"{fahrenheit}F is equal to {celsius}C")
    return celsius
  else:
    print("Invalid choice. Please enter 1 or 2.")
    return None
# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 1
Enter temperature in Celsius: 100
100.0C is equal to 212.0F


212.0

### TO - DO - Tasks

#### Exercise on Functions:

Task - 1: <BR>
Create a Python program that converts between different units of measurement.
• The program should: <BR>
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).<BR>
2. Ask the user to input the value to be converted.<BR>
3. Perform the conversion and display the result.<BR>
4. Handle potential errors, such as invalid input or unsupported conversion types.<BR>
• Requirements:<BR>
1. Functions: Define at least one function to perform the conversion.<BR>
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).<BR>
3. User Input: Prompt the user to select the conversion type and input the value.<BR>
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.<BR>
• Conversion Options:<BR>
1. Length:<BR>
– Convert meters (m) to feet (ft).<BR>
– Convert feet (ft) to meters (m).<BR>
2. Weight:<BR>
– Convert kilograms (kg) to pounds (lbs).<BR>
– Convert pounds (lbs) to kilograms (kg).<BR>
3. Volume:<BR>
– Convert liters (L) to gallons (gal).<BR>
– Convert gallons (gal) to liters (L).<BR>

In [ ]:
import numpy as np
import time

In [ ]:
def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    Parameters:
    conversion_type (str): Type of conversion to perform.
    value (float): The numeric value to convert.

    Returns:
    float: Converted value.
    """

    if conversion_type == "1":  # meters to feet
        return value * 3.28084
    elif conversion_type == "2":  # feet to meters
        return value / 3.28084
    elif conversion_type == "3":  # kg to pounds
        return value * 2.20462
    elif conversion_type == "4":  # pounds to kg
        return value / 2.20462
    elif conversion_type == "5":  # liters to gallons
        return value * 0.264172
    elif conversion_type == "6":  # gallons to liters
        return value / 0.264172
    else:
        return None


def unit_conversion_program():
    print("Choose Conversion Type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    choice = input("Enter choice (1-6): ")

    try:
        value = float(input("Enter value to convert: "))
        result = convert_units(choice, value)

        if result is None:
            print("Invalid conversion type selected.")
        else:
            print("Converted value:", result)

    except ValueError:
        print("Invalid input! Please enter a numeric value.")


unit_conversion_program()

Choose Conversion Type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter choice (1-6): 3
Enter value to convert: 12
Converted value: 26.455439999999996


Task - 2: <BR>
Create a Python program that performs various mathematical operations on a list of numbers.<BR>
• The Program should:<BR>
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).<BR>
2. Ask the user to input a list of numbers (separated by spaces).<BR>
3. Perform the selected operation and display the result. <BR>
4. Handle potential errors, such as invalid input or empty lists. <BR>
• Requirements:<BR>

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).<BR>

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).<BR>
3. User Input: Prompt the user to select the operation and input the list of numbers.<BR>
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.<BR>

In [24]:
def calculate_sum(numbers):
    """
    Returns the sum of numbers in the list.
    """
    total = 0
    for num in numbers:
        total += num
    return total


def calculate_average(numbers):
    """
    Returns the average of numbers in the list.
    """
    if len(numbers) == 0:
        return None
    return calculate_sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Returns the maximum number in the list.
    """
    maximum = numbers[0]
    for num in numbers:
        if num > maximum:
            maximum = num
    return maximum


def find_minimum(numbers):
    """
    Returns the minimum number in the list.
    """
    minimum = numbers[0]
    for num in numbers:
        if num < minimum:
            minimum = num
    return minimum


def math_operations_program():
    print("Choose Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter choice (1-4): ")

    try:
        user_input = input("Enter numbers separated by space: ")
        numbers = [float(x) for x in user_input.split()]

        if len(numbers) == 0:
            print("Empty list is not allowed.")
            return

        if choice == "1":
            print("Sum:", calculate_sum(numbers))
        elif choice == "2":
            print("Average:", calculate_average(numbers))
        elif choice == "3":
            print("Maximum:", find_maximum(numbers))
        elif choice == "4":
            print("Minimum:", find_minimum(numbers))
        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Invalid input! Please enter numeric values only.")


math_operations_program()

Choose Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1-4): 1
Enter numbers separated by space: 12 13
Sum: 25.0


4.2 Exercise on List Manipulation: <BR>
1. Extract Every Other Element: <BR>
Write a Python function that extracts every other element from a list, starting from the first element.<BR>
• Requirements:<BR>
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.<BR>
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].<BR>
2. Slice a Sublist:<BR>
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.<BR>
• Requirements:<BR>
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).<BR>
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].<BR>
3. Reverse a List Using Slicing:<BR>
Write a Python function that reverses a list using slicing.<BR>
• Requirements:<BR>
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.<BR>
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].<BR>
4. Remove the First and Last Elements:<BR>
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.<BR>
• Requirements:<BR>
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.<BR>
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].<BR>
5. Get the First n Elements:<BR>
Write a Python function that extracts the first n elements from a list.<BR>
• Requirements:<BR>
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.<BR>
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].<BR>
6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.<BR>
• Requirements:<BR>
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.<BR>
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].<BR>
7. Extract Elements in Reverse Order:<BR>
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.<BR>
• Requirements:<BR>
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.<BR>
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].<BR>

In [ ]:
def extract_every_other(lst):
    return lst[::2]


def get_sublist(lst, start, end):
    return lst[start:end+1]


def reverse_list(lst):
    return lst[::-1]


def remove_first_last(lst):
    return lst[1:-1]


def get_first_n(lst, n):
    return lst[:n]


def get_last_n(lst, n):
    return lst[-n:]


def reverse_skip(lst):
    return lst[-2::-2]

4.3 Exercise on Nested List:<BR>
1. Flatten a Nested List:<BR>
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.<BR>
• Requirements:<BR>
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.<BR>
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].<BR>
2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.<BR>
• Requirements:<BR>
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.<BR>
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.<BR>
3. Sum of All Elements in a Nested List:<BR>
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).<BR>
• Requirements:<BR>
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.<BR>
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.<BR>
4. Remove Specific Element from a Nested List:<BR>
Write a Python function that removes all occurrences of a specific element from a nested list.<BR>
• Requirements:<BR>
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.<BR>
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].<BR>

5. Find the Maximum Element in a Nested List:<BR>
Write a Python function that finds the maximum element in a nested list (regardless of depth).<BR>
• Requirements:<BR>
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.<BR>
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.<BR>
6. Count Occurrences of an Element in a Nested List:<BR>
Write a Python function that counts how many times a specific element appears in a nested list.<BR>
• Requirements:<BR>
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.<BR>

7. Flatten a List of Lists of Lists:<BR>
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.<BR>
• Requirements:<BR>
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.<BR>
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].
<BR>
8. Nested List Average:<BR>
Write a Python function that calculates the average of all elements in a nested list.<BR>
• Requirements:<BR>
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.<BR>
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.<BR>

In [25]:
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result


def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element


def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result


def find_max(lst):
    maximum = None
    for item in lst:
        if isinstance(item, list):
            value = find_max(item)
        else:
            value = item

        if maximum is None or value > maximum:
            maximum = value
    return maximum


def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


def deep_flatten(lst):
    return flatten(lst)


def average_nested(lst):
    flat_list = flatten(lst)
    if len(flat_list) == 0:
        return None
    return sum_nested(lst) / len(flat_list)

## Numpy

### Importing Numpy and Creating Arrays of Zero.

In [26]:
import numpy as np
# initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



### Creating and Displaying Different Type of Arrays.

In [27]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



### 1. .ndim Number of Dimensions: Returns the number of dimensions (axes) in the array.

In [28]:
# For a 1-D array:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim) # Output: 1
# For a 2-D array:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr_2d.ndim) # Output: 2
#For a 3-D array:
arr_3d = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print(arr_3d.ndim) # Output: 3

1
2
3


### 2. .shape Shape of the Array: Returns a tuple representing the size of each dimension.

In [29]:
print(arr_1d.shape) # Output: (5,)
print(arr_2d.shape) # Output: (2, 3)
print(arr_3d.shape) # Output: (2, 2, 3)

(5,)
(2, 3)
(2, 2, 3)


### 3. .size Total Number of Elements: Returns the total number of elements in the array.

In [30]:
print(arr_1d.size) # Output: 5
print(arr_2d.size) # Output: 6
print(arr_3d.size) # Output: 12

5
6
12


### .dtype Data Type of Elements: Returns the data type of the array elements.

In [31]:
print(arr_1d.dtype) # Output: int64 (or int32)
arr_float = np.array([1.1, 2.2, 3.3])
print(arr_float.dtype) # Output: float64

int64
float64


### 5. .itemsize Size of Each Element in Bytes: Returns the size (in bytes) of one array element.

In [32]:
print(arr_1d.itemsize) # Output: 8 (for int64)

8


### 6. .nbytes Total Memory Consumption: Returns the total memory (in bytes) used by the array.

In [33]:
print(arr_1d.nbytes) # Output: 40 (5 elements \times 8 bytes each for int64)

40


### 7. .T Transpose of the Array: Returns the transposed version of the array.

In [34]:
print(arr_2d.T)
# Output:
# [[1 4]
# [2 5]
# [3 6]]

[[1 4]
 [2 5]
 [3 6]]


### 8. .flat Flattening the Array: Returns an iterator over a 1D representation of the array.

In [35]:
for item in arr_2d.flat:
  print(item, end=" ") # Output: 1 2 3 4 5 6

1 2 3 4 5 6 

### 9. .real and .imag - Real and Imaginary Parts: Used for complex number arrays.

In [36]:
arr_complex = np.array([1+2j, 3+4j])
print(arr_complex.real) # Output: [1. 3.]
print(arr_complex.imag) # Output: [2. 4.]

[1. 3.]
[2. 4.]


### 10. .astype(dtype) Convert Data Type: Converts the array elements to a specified data type.

In [37]:
arr_float = arr_2d.astype(float)
print(arr_float)
# Output:
# [[1. 2. 3.]
# [4. 5. 6.]]

[[1. 2. 3.]
 [4. 5. 6.]]


### NumPy ndarray - reshape:

In [39]:
import numpy as np
# Create an array with shape (2, 3)
array = np.array([[1, 2, 3],
[4, 5, 6]])

# Reshape to (3, 2), keeping 6 elements
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)
# Expected Outputs:
# Original Shape: (2, 3)
# Reshaped Shape: (3, 2)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


Using in-built function - Arrays with Evenly spaced values: <BR>
– arange: The syntax of arange is arange([start,]stop[,step],[,dtype=None])
<BR>
Example - arange

In [40]:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


– linspace: The syntax is linpspace(start,stop,num=50,endpoint=True,retstep=False)
<BR>
Example - linspace

In [41]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


### Creating or Initializing with Ones, Zeros and Empty:

– np.ones: Creates an array of ones as specified by shape.The syntax is: np.ones(shape,
dtype = None) <BR>
– np.zeros: Creates an array of zeros as specified by shape.The syntax is: np.zeros(shape,
dtype=None)<BR>
– np.empty: Creates an array of uninitialized values of the specified shape.The syntax is:
np.empty(shape, dtype=None). <BR>
– np.eye(N): Creates an identity matrix of shape (N, N) filled with ones on the diagonal and
zeros elsewhere.

In [43]:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[1.34094477e-315 0.00000000e+000]
 [5.73116149e-322 5.28650241e-322]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### By Manipulating Existing Array: <BR> Example - Using ndarray.

In [45]:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


### By Manipulating Existing Array: <BR> Example - Using shape of an existing array.

In [47]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) #
Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.34288854e-315 0.00000000e+000 6.79038654e-313]
 [6.79038653e-313 6.58285534e-310 6.58297711e-310]]


### By Combining or joining array: <BR> Example - Implementing np.hstack() and np.vstack()

In [51]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


### By Combining or joining array: <BR> Example - Implementing np.concatenate()

In [52]:
import numpy as np
# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]]) # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]]) # Shape: (2, 2, 1)
# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (third dimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)

Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


## Array Slicing and Indexing.

### Array Indexing and Slicing.

In [53]:
import numpy as np
# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing elements using indexing
print(array[0, 1]) # Output: 2 (first row, second column)
print(array[-1, -1]) # Output: 9 (last row, last column)
# Slicing the array
print(array[0:2, 1:3]) # Output: [[2, 3], [5, 6]]

2
9
[[2 3]
 [5 6]]


## Array Mathematics with NumPy.

### Example - Universal Functions.

In [54]:
import numpy as np
# Example of basic ufuncs: square and square root
arr = np.array([1, 4, 9, 16])
# Square every element
squared = np.square(arr)
# Square root of every element
sqrt = np.sqrt(arr)
print(f"Squared: {squared}")
print(f"Square root: {sqrt}")

Squared: [  1  16  81 256]
Square root: [1. 2. 3. 4.]


### Example - Mathematical ufuncs.

In [55]:
import numpy as np
# Trigonometric ufuncs
angles = np.array([0, np.pi / 4, np.pi / 2])
sine_values = np.sin(angles)
# Logarithmic ufuncs
log_values = np.log(arr)

### Sample Use of np.linalg

In [56]:
import numpy as np
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
# Compute determinant
det = np.linalg.det(A)
# Compute inverse
inverse = np.linalg.inv(A)
# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(f"Matrix Product:\n{product}")
print(f"Determinant: {det}")
print(f"Inverse:\n{inverse}")
print(f"Eigenvalues: {eigvals}, Eigenvectors:\n{eigvecs}")

Matrix Product:
[[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132], Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Valid Broadcasting - Column Matches.

In [57]:
import numpy as np
A = np.array([[1], [2], [3]]) # Shape (3,1) 3 rows, 1 column
B = np.array([10, 20, 30]) # Shape (3,) 1D array (3 elements)
C = A + B # Works! Result shape: (3,3)
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### Valid Broadcasting - Row Matches.

In [58]:
A = np.array([[1, 2, 3]]) # Shape (1,3)
B = np.array([[4], [5], [6]]) # Shape (3,1)
C = A + B #Works! Result shape: (3,3)
print(C)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


### Python Loop vs. NumPy Vectorizations.

In [60]:
import numpy as np
import time
# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)
# Using a loop
start_time = time.time()
result_loop = np.zeros(size)
for i in range(size):
  result_loop[i] = a[i] + b[i]
end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")
# Using NumPy’s vectorized operations
start_time = time.time()
result_vectorized = a + b # Element-wise addition
end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")
# Performance improvement factor
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 0.52001 seconds
Vectorized Execution Time: 0.00330 seconds
Vectorization is approximately 157.38 times faster!


TO - DO - Numpy

Problem - 1: Array Creation: <BR>
Complete the following Tasks: <BR>
1. Initialize an empty array with size 2X2.<BR>
2. Initialize an all one array with size 4X2.<BR>
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}<BR>
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}<BR>
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}<BR>
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}<BR>

In [61]:
# 1. Empty array 2x2
arr1 = np.empty((2,2))

# 2. All ones array 4x2
arr2 = np.ones((4,2))

# 3. Array filled with given value
arr3 = np.full((3,3), 7)

# 4. Zeros like existing array
arr4 = np.zeros_like(arr2)

# 5. Ones like existing array
arr5 = np.ones_like(arr2)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
arr6 = np.array(new_list)

print(arr1, "\n")
print(arr2, "\n")
print(arr3, "\n")
print(arr4, "\n")
print(arr5, "\n")
print(arr6)

[[2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

[[7 7 7]
 [7 7 7]
 [7 7 7]] 

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

[1 2 3 4]


Problem - 2: Array Manipulation: <BR>Numerical Ranges and Array indexing:<BR>
Complete the following tasks:<BR>
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.<BR>
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}<BR>
3. Create a 3X3 identity matrix.{Hint:np.eye()}<BR>
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}<BR>
5. Create a 10X10 array with random values and find the minimum and maximum values.<BR>
6. Create a zero array of size 10 and replace 5th element with 1.<BR>
7. Reverse an array arr = [1,2,0,0,4,0].<BR>
8. Create a 2d array with 1 on border and 0 inside.<BR>
9. Create a 8X8 matrix and fill it with a checkerboard pattern.<BR>

In [62]:
# 1. Values from 10 to 49
arr1 = np.arange(10,50)

# 2. 3x3 matrix from 0 to 8
arr2 = np.arange(9).reshape(3,3)

# 3. Identity matrix
arr3 = np.eye(3)

# 4. Random array size 30 and mean
arr4 = np.random.random(30)
mean_value = arr4.mean()

# 5. 10x10 random array with min and max
arr5 = np.random.random((10,10))
min_val = arr5.min()
max_val = arr5.max()

# 6. Zero array size 10, replace 5th element
arr6 = np.zeros(10)
arr6[4] = 1

# 7. Reverse array
arr7 = np.array([1,2,0,0,4,0])
reversed_arr = arr7[::-1]

# 8. 2D array with 1 on border and 0 inside
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0

# 9. 8x8 checkerboard pattern
arr9 = np.zeros((8,8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1

print(arr1)
print(arr2)
print(arr3)
print("Mean:", mean_value)
print("Min:", min_val, "Max:", max_val)
print(arr6)
print(reversed_arr)
print(arr8)
print(arr9)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean: 0.47114207635415173
Min: 0.0010563069407892867 Max: 0.9977109866379239
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:<BR>
For the following arrays:<BR>
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);<BR>
v = np.array([9,10]) and w = np.array([11,12]);<BR>
Complete all the task using numpy:<BR>
1. Add the two array.<BR>
2. Subtract the two array.<BR>
3. Multiply the array with any integers of your choice.<BR>
4. Find the square of each element of the array.<BR>
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.<BR>
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.<BR>
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?<BR>

In [63]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Addition
print("Addition:\n", x + y)

# 2. Subtraction
print("Subtraction:\n", x - y)

# 3. Multiply with integer
print("Multiply x by 3:\n", x * 3)

# 4. Square each element
print("Square of x:\n", x**2)

# 5. Dot Products
print("v.w:", np.dot(v,w))
print("x.v:", np.dot(x,v))
print("x.y:\n", np.dot(x,y))

# 6. Concatenation
print("Concatenate x & y (rows):\n", np.concatenate((x,y), axis=0))
print("Concatenate v & w (columns):\n", np.vstack((v,w)))

# 7. Concatenate x & v
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("Error:", e)

Addition:
 [[ 6  8]
 [10 13]]
Subtraction:
 [[-4 -4]
 [-4 -3]]
Multiply x by 3:
 [[ 3  6]
 [ 9 15]]
Square of x:
 [[ 1  4]
 [ 9 25]]
v.w: 219
x.v: [29 77]
x.y:
 [[19 22]
 [50 58]]
Concatenate x & y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v & w (columns):
 [[ 9 10]
 [11 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations: <BR>
• For the following arrays:<BR>
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);<BR>
Prove following with Numpy:<BR>
1. Prove A.A−1 = I.<BR>
2. Prove AB ̸= BA.
3. Prove (AB)
<BR>
T = BTAT<BR>
.

• Solve the following system of Linear equation using Inverse Methods.<BR>

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}<BR>

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}<BR>

In [64]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A_inv:\n", np.dot(A, A_inv))

# 2. Prove AB ≠ BA
print("AB:\n", np.dot(A,B))
print("BA:\n", np.dot(B,A))

# 3. Prove (AB)^T = B^T A^T
left = np.dot(A,B).T
right = np.dot(B.T, A.T)
print("Left:\n", left)
print("Right:\n", right)

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Left:
 [[23 51]
 [13 29]]
Right:
 [[23 51]
 [13 29]]


In [65]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

# Solve using inverse
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution using inverse:", X)

# Direct method using linalg.solve
X2 = np.linalg.solve(A,B)
print("Solution using solve:", X2)

Solution using inverse: [ 2.  1. -2.]
Solution using solve: [ 2.  1. -2.]


Experiment: How Fast is Numpy?<BR>
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:<BR>
1. Element-wise Addition:<BR>
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.<BR>
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.<BR>
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.<BR>
Measure and Print the time taken for this operation.<BR>
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.<BR>
3. Dot Product<BR>
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.<BR>
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.<BR>
4. Matrix Multiplication<BR>
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.<BR>
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.<BR>

In [66]:
size = 1000000

# Python Lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
print("Python List Addition Time:", time.time() - start)

# NumPy
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
result = arr1 + arr2
print("NumPy Addition Time:", time.time() - start)

Python List Addition Time: 0.0653829574584961
NumPy Addition Time: 0.008936166763305664


In [67]:
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
print("Python List Multiplication Time:", time.time() - start)

start = time.time()
result = arr1 * arr2
print("NumPy Multiplication Time:", time.time() - start)

Python List Multiplication Time: 0.08145260810852051
NumPy Multiplication Time: 0.008546113967895508


In [68]:
start = time.time()
dot = sum(list1[i] * list2[i] for i in range(size))
print("Python Dot Product Time:", time.time() - start)

start = time.time()
dot = np.dot(arr1, arr2)
print("NumPy Dot Product Time:", time.time() - start)

Python Dot Product Time: 0.06397056579589844
NumPy Dot Product Time: 0.0011296272277832031


In [69]:
size = 1000

A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start = time.time()
result = [[sum(A[i][k] * B[k][j] for k in range(size))
           for j in range(size)] for i in range(size)]
print("Python Matrix Multiplication Time:", time.time() - start)

A_np = np.ones((size,size))
B_np = np.ones((size,size))

start = time.time()
result = np.dot(A_np, B_np)
print("NumPy Matrix Multiplication Time:", time.time() - start)

Python Matrix Multiplication Time: 76.35869550704956
NumPy Matrix Multiplication Time: 0.05917835235595703
